language: ruby
sudo: false
rvm:
  - 2.2.0
before_script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
script:
  - bundle exec rubocop --only-guide-cops app/
  - RAILS_ENV=test bundle exec rspec
